export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const header = (
    <header>
      <div>
        <h1>KT's Blog</h1>
        <p>GGWP</p>
      </div>
    </header>
  );

  const footer = (
    <header>
      <div>
        <h3>Developed by KT</h3>
      </div>
    </header>
  );


  return (
    <html>
      <head />
      <body>
        {header}
        {children}
        {footer}
      </body>
    </html>
  )
}
